# Generated by Django 3.1.2 on 2020-10-15 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('lecturer', models.CharField(max_length=25)),
                ('sks', models.CharField(max_length=2)),
                ('desc', models.CharField(max_length=200)),
                ('year', models.CharField(max_length=20)),
                ('kls', models.CharField(max_length=10)),
            ],
        ),
    ]
