# Generated by Django 3.1.2 on 2020-10-23 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('story6', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participant',
            old_name='activ_name',
            new_name='activity',
        ),
        migrations.RenameField(
            model_name='participant',
            old_name='contact_num',
            new_name='contact_number',
        ),
    ]
