# Generated by Django 3.1.2 on 2020-10-24 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story6', '0003_auto_20201024_0947'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='name',
        ),
        migrations.AddField(
            model_name='activity',
            name='actname',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='participant',
            name='contact_number',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AlterField(
            model_name='participant',
            name='name',
            field=models.CharField(default='', max_length=20),
        ),
    ]
